INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('1','Accountant','Emely_Hudson1571@nickia.com','Emely','Hudson','Facebook');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('2','Project Manager','Lily_Whitehouse1117@cispeto.com','Lily','Whitehouse','Telekom');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('3','HR Coordinator','Ada_Mann2234@qater.org','Ada','Mann','Areon Impex');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('4','Assistant Buyer','Monica_Gunn3057@atink.com','Monica','Gunn','Leadertech Consulting');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('5','Bellman','Marvin_Hobbs8386@naiker.biz','Marvin','Hobbs','Coca-Cola Company');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('6','Assistant Buyer','Chad_Knight3056@acrit.org','Chad','Knight','CarMax');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('7','Chef Manager','Johnny_Bell5015@extex.org','Johnny','Bell','DynCorp');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('8','Design Engineer','Tom_Moore7252@muall.tech','Tom','Moore','ENEL');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('9','Doctor','Melinda_Hobson5059@twace.org','Melinda','Hobson','Areon Impex');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('10','Biologist','Alison_Adams7158@muall.tech','Alison','Adams','Metro Cash&Carry');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('11','HR Coordinator','Barry_Dallas5059@infotech44.tech','Barry','Dallas','Danone');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('12','Inspector','Rosalee_Casey1560@brety.org','Rosalee','Casey','It Smart Group');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('13','Retail Trainee','Chloe_Blythe1305@grannar.com','Chloe','Blythe','Biolife Grup');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('14','Inspector','Felicity_Gallacher2164@yahoo.com','Felicity','Gallacher','Apple Inc.');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('15','Healthcare Specialist','Shannon_Fox3551@joiniaa.com','Shannon','Fox','Apple Inc.');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('16','Machine Operator','Vicky_Ianson6828@ubusive.com','Vicky','Ianson','Apple Inc.');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('17','Staffing Consultant','Robyn_Jenkin3977@typill.biz','Robyn','Jenkin','Apple Inc.');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('18','Audiologist','Marilyn_Walker834@naiker.biz','Marilyn','Walker','Zepter');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('19','Baker','Carissa_Squire9358@sheye.org','Carissa','Squire','ENEL');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('20','Webmaster','Matt_Pond3160@sheye.org','Matt','Pond','Vodafone');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('21','Machine Operator','Vicky_Weatcroft2206@twipet.com','Vicky','Weatcroft','Vodafone');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('22','Systems Administrator','Victoria_Allwood2257@fuliss.net','Victoria','Allwood','Comcast');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('23','Design Engineer','Valerie_Marshall6284@muall.tech','Valerie','Marshall','AECOM');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('24','Bookkeeper','Brooklyn_Davies5649@zorer.org','Brooklyn','Davies','Demaco');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('25','Bellman','Jazmin_Niles363@sveldo.biz','Jazmin','Niles','Areon Impex');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('26','Investment  Advisor','Tony_Wild4991@cispeto.com','Tony','Wild','UPC');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('27','Electrician','Elise_Hunter7642@dionrab.com','Elise','Hunter','Boeing');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('28','Stockbroker','Caleb_Stevens1235@deavo.com','Caleb','Stevens','Danone');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('29','Inspector','Tess_Weston4103@vetan.org','Tess','Weston','ENEL');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('30','Auditor','Boris_Cunningham8932@kideod.biz','Boris','Cunningham','Danone');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('31','Pharmacist','Lucas_Robertson1453@famism.biz','Lucas','Robertson','ExxonMobil');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('32','IT Support Staff','William_Pond8063@bauros.biz','William','Pond','DynCorp');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('33','Bellman','Molly_Jefferson4106@typill.biz','Molly','Jefferson','Mars');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('34','Audiologist','Elijah_Kirby8992@fuliss.net','Elijah','Kirby','DynCorp');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('35','Global Logistics Supervisor','Caleb_Ballard6103@brety.org','Caleb','Ballard','Carrefour');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('36','Laboratory Technician','Gemma_Clark6655@acrit.org','Gemma','Clark','Boeing');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('37','Software Engineer','Manuel_Hancock8662@iatim.tech','Manuel','Hancock','Leadertech Consulting');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('38','Design Engineer','John_Ogilvy6405@gmail.com','John','Ogilvy','ExxonMobil');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('39','Retail Trainee','Bart_Parr220@infotech44.tech','Bart','Parr','Apple Inc.');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('40','Webmaster','Carter_Norman146@brety.org','Carter','Norman','ENEL');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('41','Operator','Helen_Dixon4738@bulaffy.com','Helen','Dixon','ExxonMobil');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('42','Front Desk Coordinator','Jamie_Pickard3865@eirey.tech','Jamie','Pickard','BuzzFeed');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('43','Associate Professor','Tania_Cobb3578@ubusive.com','Tania','Cobb','Danone');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('44','Cook','Sofia_Griffiths3768@cispeto.com','Sofia','Griffiths','ExxonMobil');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('45','Loan Officer','Lucas_Tanner9015@sveldo.biz','Lucas','Tanner','CarMax');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('46','Design Engineer','Boris_Mcnally4560@infotech44.tech','Boris','Mcnally','Boeing');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('47','Budget Analyst','Barry_Chapman7125@kideod.biz','Barry','Chapman','Apple Inc.');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('48','Mobile Developer','Vanessa_Lewin3991@ubusive.com','Vanessa','Lewin','CarMax');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('49','Retail Trainee','Savannah_Forth4086@fuliss.net','Savannah','Forth','Biolife Grup');
INSERT INTO customer (ID, JOBTITLE, EMAIL, FIRSTNAME, LASTNAME, COMPANY) VALUES('50','Dentist','Hank_Patel1525@bulaffy.com','Hank','Patel','BuzzFeed');